PROG' -> PROG
PROG -> TOPS
TOPS -> TOPS TOP
TOPS -> TOP
TOP -> CASE_CLASS_DEF
TOP -> FUNC_DEF
CASE_CLASS_DEF -> CASE CLASS ID LPAREN CLASS_PARAMS RPAREN SEMI
CLASS_PARAMS -> CLASS_PARAMS COMMA CLASS_PARAM
CLASS_PARAMS -> CLASS_PARAM
CLASS_PARAM -> ID COLON TYPE
FUNC_DEF -> DEF ID LPAREN OPT_PARAMS RPAREN COLON TYPE ASSIGN BLOCK
OPT_PARAMS -> 
OPT_PARAMS -> PARAMS
PARAMS -> PARAMS COMMA PARAM
PARAMS -> PARAM
PARAM -> ID COLON TYPE
TYPE -> SIMPLE_TYPE
TYPE -> SIMPLE_TYPE LBRACKET TYPE RBRACKET
SIMPLE_TYPE -> ID
BLOCK -> LBRACE STMTS RBRACE
STMTS -> 
STMTS -> STMTS STMT
STMT -> VAR_DECL SEMI
STMT -> ASSIGN_STMT SEMI
STMT -> RETURN_STMT SEMI
STMT -> EXPR_STMT SEMI
STMT -> IF_STMT
STMT -> WHILE_STMT
STMT -> BLOCK
VAR_DECL -> VAR ID COLON TYPE ASSIGN EXPR
VAR_DECL -> VAR ID ASSIGN EXPR
ASSIGN_STMT -> LVALUE ASSIGN EXPR
ASSIGN_STMT -> LVALUE ADD_ASSIGN EXPR
ASSIGN_STMT -> LVALUE SUB_ASSIGN EXPR
LVALUE -> POSTFIX
RETURN_STMT -> RETURN EXPR
EXPR_STMT -> EXPR
IF_STMT -> IF LPAREN EXPR RPAREN STMT
IF_STMT -> IF LPAREN EXPR RPAREN STMT ELSE STMT
WHILE_STMT -> WHILE LPAREN EXPR RPAREN STMT
EXPR -> OR_EXPR
OR_EXPR -> OR_EXPR OR AND_EXPR
OR_EXPR -> AND_EXPR
AND_EXPR -> AND_EXPR AND EQ_EXPR
AND_EXPR -> EQ_EXPR
EQ_EXPR -> EQ_EXPR EQ REL_EXPR
EQ_EXPR -> EQ_EXPR NE REL_EXPR
EQ_EXPR -> REL_EXPR
REL_EXPR -> REL_EXPR LT ADD_EXPR
REL_EXPR -> REL_EXPR LE ADD_EXPR
REL_EXPR -> REL_EXPR GT ADD_EXPR
REL_EXPR -> REL_EXPR GE ADD_EXPR
REL_EXPR -> ADD_EXPR
ADD_EXPR -> ADD_EXPR PLUS MUL_EXPR
ADD_EXPR -> ADD_EXPR MINUS MUL_EXPR
ADD_EXPR -> MUL_EXPR
MUL_EXPR -> MUL_EXPR STAR UNARY_EXPR
MUL_EXPR -> MUL_EXPR SLASH UNARY_EXPR
MUL_EXPR -> MUL_EXPR PERCENT UNARY_EXPR
MUL_EXPR -> UNARY_EXPR
UNARY_EXPR -> NOT UNARY_EXPR
UNARY_EXPR -> MINUS UNARY_EXPR
UNARY_EXPR -> POSTFIX
POSTFIX -> POSTFIX DOT ID
POSTFIX -> POSTFIX LPAREN OPT_ARGS RPAREN
POSTFIX -> POSTFIX LBRACKET EXPR RBRACKET
POSTFIX -> PRIMARY
OPT_ARGS -> 
OPT_ARGS -> ARGS
ARGS -> ARGS COMMA EXPR
ARGS -> EXPR
PRIMARY -> ID
PRIMARY -> NUM_INT
PRIMARY -> NUM_DEC
PRIMARY -> NUM_HEX
PRIMARY -> NUM_LONG
PRIMARY -> STRING
PRIMARY -> TRUE
PRIMARY -> FALSE
PRIMARY -> LPAREN EXPR RPAREN
PRIMARY -> NEW ID LBRACKET TYPE RBRACKET LPAREN EXPR RPAREN
